<template>
	<div class="q-pa-md">
		<div>&nbsp;</div>
		<q-separator class="bg-red-10"></q-separator>
		<div class="text-h6 text-negative">
			Lista de Contactos para Tratamento - {{ title }}
		</div>
		<q-separator class="bg-red-10"></q-separator>
		<div>&nbsp;</div>
		<q-card style="border: 2px solid #df091d;">
			<q-card-section>
				<div class="q-pa-md">
					<q-table style="height: 400px" flat bordered title="Treats" :rows="rows" :columns="columns"
						row-key="index" virtual-scroll :rows-per-page-options="[0]">
						<template v-slot:body-cell-actions="props">
							<q-td :props="props">
								<q-checkbox keep-color v-model="cyan" color="cyan" />
								<q-btn icon="delete" flat round color="red"></q-btn>
								<q-btn icon="person" size="10px" round color="blue"></q-btn>
								<q-btn icon="content_copy" flat round color="blue"></q-btn>
								<q-btn icon="info" flat round color="blue"></q-btn>
							</q-td>
						</template>
					</q-table>
				</div>
			</q-card-section>
		</q-card>

	</div>
</template>
<script lang="ts">
import { defineComponent, ref } from 'vue'

export default defineComponent({
	name: 'BoardComponent',
	props: {
		title: {
			type: String,
			required: true
		}
	},
	setup () {
		const cyan = ref(false)
		const columns = [
			{
				name: 'actions',
				required: true,
				label: 'Actions',
				align: 'left',
				field: row => row.name,
				format: val => `${val}`,
				sortable: true
			},

			{ name: 'origem', align: 'center', label: 'Origem', field: 'origem' },
			{ name: 'evento', align: 'left', label: 'Evento', field: 'evento' },
			{ name: 'dataEvento', align: 'left', label: 'Data Evento', field: 'dataEvento' },
			{ name: 'concessão', align: 'left', label: 'Concessão', field: 'concessão' },
			{ name: 'nif', align: 'left', label: 'NIF', field: 'nif' },
			{ name: 'nome', align: 'left', label: 'Nome', field: 'nome' },
			{ name: 'codPostal', align: 'left', label: 'Cod. Postal', field: 'codPostal' },
			{ name: 'morada', align: 'left', label: 'Morada', field: 'morada' },
			{ name: 'localidade', align: 'left', label: 'Localidade', field: 'localidade' },
			{ name: 'email', align: 'left', label: 'Email', field: 'email' },
			{ name: 'telefone1', align: 'left', label: 'Telefone 1', field: 'telefone1' },
			{ name: 'telefone2', align: 'left', label: 'Telefone 2', field: 'telefone2' },
			{ name: 'telefone3', align: 'left', label: 'Telefone 3', field: 'telefone3' },
			{ name: 'matricula', align: 'left', label: 'Matrícula', field: 'matricula' },
			{ name: 'optionP', align: 'left', label: 'P', field: 'optionPP' },
			{ name: 'optionU', align: 'left', label: 'U', field: 'optionU' },
			{ name: 'optionF', align: 'left', label: 'F', field: 'optionF' },
			{ name: 'vin', align: 'left', label: 'VIN', field: 'vin' },
			{ name: 'marca', align: 'left', label: 'Marca', field: 'marca' },
			{ name: 'modelo', align: 'left', label: 'Modelo', field: 'modelo' },
			{ name: 'versão', align: 'left', label: 'Versão', field: 'versão' },
			{ name: 'cor', align: 'left', label: 'Cor', field: 'cor' }
		]
		const rows = [
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD AUTOMOTIVE-Soc.Ger.Com.Alg.Bens,Ld',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park-ed.2 E.Oc ZONA INDUST.ABRUNHEIRA',
				localidade: 'SINTRA',
				email: '',
				telefone1: '210920392',
				telefone2: '',
				telefone3: '',
				matricula: '67IN93',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: 'TW1ZT52Y609501009',
				marca: 'Toyota',
				modelo: 'DYNA M 35.33 CT 3.5',
				versão: 'Dyna M CT 35.33',
				cor: 'BRANCO 058'
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD Automotive, SA (Colisão)',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park - Zn Ind',
				localidade: 'SINTRA',
				email: 'info@aldautomotive.com',
				telefone1: '289500104',
				telefone2: '',
				telefone3: '210920364',
				matricula: '32NN75',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: '',
				marca: '',
				modelo: '',
				versão: '',
				cor: ''
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD AUTOMOTIVE-Soc.Ger.Com.Alg.Bens,Ld',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park-ed.2 E.Oc ZONA INDUST.ABRUNHEIRA',
				localidade: 'SINTRA',
				email: '',
				telefone1: '210920392',
				telefone2: '',
				telefone3: '',
				matricula: '67IN93',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: 'TW1ZT52Y609501009',
				marca: 'Toyota',
				modelo: 'DYNA M 35.33 CT 3.5',
				versão: 'Dyna M CT 35.33',
				cor: 'BRANCO 058'
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD Automotive, SA (Colisão)',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park - Zn Ind',
				localidade: 'SINTRA',
				email: 'info@aldautomotive.com',
				telefone1: '289500104',
				telefone2: '',
				telefone3: '210920364',
				matricula: '32NN75',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: '',
				marca: '',
				modelo: '',
				versão: '',
				cor: ''
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD AUTOMOTIVE-Soc.Ger.Com.Alg.Bens,Ld',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park-ed.2 E.Oc ZONA INDUST.ABRUNHEIRA',
				localidade: 'SINTRA',
				email: '',
				telefone1: '210920392',
				telefone2: '',
				telefone3: '',
				matricula: '67IN93',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: 'TW1ZT52Y609501009',
				marca: 'Toyota',
				modelo: 'DYNA M 35.33 CT 3.5',
				versão: 'Dyna M CT 35.33',
				cor: 'BRANCO 058'
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD Automotive, SA (Colisão)',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park - Zn Ind',
				localidade: 'SINTRA',
				email: 'info@aldautomotive.com',
				telefone1: '289500104',
				telefone2: '',
				telefone3: '210920364',
				matricula: '32NN75',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: '',
				marca: '',
				modelo: '',
				versão: '',
				cor: ''
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD AUTOMOTIVE-Soc.Ger.Com.Alg.Bens,Ld',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park-ed.2 E.Oc ZONA INDUST.ABRUNHEIRA',
				localidade: 'SINTRA',
				email: '',
				telefone1: '210920392',
				telefone2: '',
				telefone3: '',
				matricula: '67IN93',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: 'TW1ZT52Y609501009',
				marca: 'Toyota',
				modelo: 'DYNA M 35.33 CT 3.5',
				versão: 'Dyna M CT 35.33',
				cor: 'BRANCO 058'
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD Automotive, SA (Colisão)',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park - Zn Ind',
				localidade: 'SINTRA',
				email: 'info@aldautomotive.com',
				telefone1: '289500104',
				telefone2: '',
				telefone3: '210920364',
				matricula: '32NN75',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: '',
				marca: '',
				modelo: '',
				versão: '',
				cor: ''
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD AUTOMOTIVE-Soc.Ger.Com.Alg.Bens,Ld',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park-ed.2 E.Oc ZONA INDUST.ABRUNHEIRA',
				localidade: 'SINTRA',
				email: '',
				telefone1: '210920392',
				telefone2: '',
				telefone3: '',
				matricula: '67IN93',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: 'TW1ZT52Y609501009',
				marca: 'Toyota',
				modelo: 'DYNA M 35.33 CT 3.5',
				versão: 'Dyna M CT 35.33',
				cor: 'BRANCO 058'
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD Automotive, SA (Colisão)',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park - Zn Ind',
				localidade: 'SINTRA',
				email: 'info@aldautomotive.com',
				telefone1: '289500104',
				telefone2: '',
				telefone3: '210920364',
				matricula: '32NN75',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: '',
				marca: '',
				modelo: '',
				versão: '',
				cor: ''
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD AUTOMOTIVE-Soc.Ger.Com.Alg.Bens,Ld',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park-ed.2 E.Oc ZONA INDUST.ABRUNHEIRA',
				localidade: 'SINTRA',
				email: '',
				telefone1: '210920392',
				telefone2: '',
				telefone3: '',
				matricula: '67IN93',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: 'TW1ZT52Y609501009',
				marca: 'Toyota',
				modelo: 'DYNA M 35.33 CT 3.5',
				versão: 'Dyna M CT 35.33',
				cor: 'BRANCO 058'
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD Automotive, SA (Colisão)',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park - Zn Ind',
				localidade: 'SINTRA',
				email: 'info@aldautomotive.com',
				telefone1: '289500104',
				telefone2: '',
				telefone3: '210920364',
				matricula: '32NN75',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: '',
				marca: '',
				modelo: '',
				versão: '',
				cor: ''
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD AUTOMOTIVE-Soc.Ger.Com.Alg.Bens,Ld',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park-ed.2 E.Oc ZONA INDUST.ABRUNHEIRA',
				localidade: 'SINTRA',
				email: '',
				telefone1: '210920392',
				telefone2: '',
				telefone3: '',
				matricula: '67IN93',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: 'TW1ZT52Y609501009',
				marca: 'Toyota',
				modelo: 'DYNA M 35.33 CT 3.5',
				versão: 'Dyna M CT 35.33',
				cor: 'BRANCO 058'
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD Automotive, SA (Colisão)',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park - Zn Ind',
				localidade: 'SINTRA',
				email: 'info@aldautomotive.com',
				telefone1: '289500104',
				telefone2: '',
				telefone3: '210920364',
				matricula: '32NN75',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: '',
				marca: '',
				modelo: '',
				versão: '',
				cor: ''
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD AUTOMOTIVE-Soc.Ger.Com.Alg.Bens,Ld',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park-ed.2 E.Oc ZONA INDUST.ABRUNHEIRA',
				localidade: 'SINTRA',
				email: '',
				telefone1: '210920392',
				telefone2: '',
				telefone3: '',
				matricula: '67IN93',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: 'TW1ZT52Y609501009',
				marca: 'Toyota',
				modelo: 'DYNA M 35.33 CT 3.5',
				versão: 'Dyna M CT 35.33',
				cor: 'BRANCO 058'
			},
			{
				origem: '',
				evento: '',
				dataEvento: '',
				nif: 503188620,
				nome: 'SGALD Automotive, SA (Colisão)',
				codPostal: '2710 - 089',
				morada: 'Rua Sintra Business Park - Zn Ind',
				localidade: 'SINTRA',
				email: 'info@aldautomotive.com',
				telefone1: '289500104',
				telefone2: '',
				telefone3: '210920364',
				matricula: '32NN75',
				optionP: 'true',
				optionU: 'false',
				optionF: 'false',
				vin: '',
				marca: '',
				modelo: '',
				versão: '',
				cor: ''
			}
		]

		const hasData = ref(true)
		return {
			columns,
			rows,
			hasData,
			hideBottom: ref(false),
			hideSelectedBanner: ref(false),
			hideNoData: ref(false),
			hidePagination: ref(false),
			cyan,

			selected: ref([rows[1]])
		}
	}
})
</script>
